# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 编程絮语
email: brep@sohu.com
description: > # this means to ignore newlines until "baseurl:"
  记录每日学到的点点滴滴，好记性不如烂笔头
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zawos.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: ibrep

# Build settings
markdown: kramdown

theme: jekyll-theme-modernist

#collections:
#        - loongson:
#                output: true

